stages:
  - deploy

deploy_dev1:
  stage: deploy
  tags: 
  - deploy
  script:
  - dpl --provider=script --script="./deploy.sh tcr-develop-app"
  only:
  - develop

deploy_dev2:
  stage: deploy
  tags: 
  - deploy
  script:
  - dpl --provider=script --script="./deploy.sh tcr-dev2-app"
  only:
  - ipfs-integration

deploy_production:
  stage: deploy
  tags: 
  - deploy
  script:
  - dpl --provider=script --script="./deploy.sh tcr-app"
  only:
  - master
