// app actions
export const APP_INIT = 'APP_INIT';
export const CHANGE_REGISTRY = 'CHANGE_REGISTRY';
export const CHANGE_BACKEND_USAGE = 'CHANGE_BACKEND_USAGE';
export const UPDATE_REGISTRIES_LIST = 'UPDATE_REGISTRIES_LIST';
export const SEND_TRANSACTIONS = 'SEND_TRANSACTIONS';
export const ADD_REGISTRY = 'ADD_REGISTRY';
export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';
export const SHOW_TRANSACTIONS_MODAL = 'SHOW_TRANSACTIONS_MODAL';
export const REGISTRY_CHANGED = 'REGISTRY_CHANGED';
export const REQUEST_PARAMETERIZER_INFORMATION = 'REQUEST_PARAMETERIZER_INFORMATION';
export const CHALLENGE_SHOW_TX_QUEUE = 'CHALLENGE_SHOW_TX_QUEUE';
export const UPDATE_PARAMETERIZER_INFORMATION = 'UPDATE_PARAMETERIZER_INFORMATION';

// consumer
export const REQUEST_CONSUMER_LISTINGS = 'REQUEST_CONSUMER_LISTINGS';
export const GET_LISTING_DATA = 'GET_LISTING_DATA';
export const UPDATE_CONSUMER_LISTINGS = 'UPDATE_CONSUMER_LISTINGS';
export const UPDATE_LISTING_DATA = 'UPDATE_LISTING_DATA';

// candidate
export const BUY_TOKENS = 'BUY_TOKENS';
export const REQUEST_TOKEN_INFORMATION = 'REQUEST_TOKEN_INFORMATION';
export const SEND_TEST_TXS = 'SEND_TEST_TXS';
export const REQUEST_CANDIDATE_LISTINGS = 'REQUEST_CANDIDATE_LISTINGS';
export const APPLY_LISTING = 'APPLY_LISTING';
export const HIDE_TX_QUEUE = 'HIDE_TX_QUEUE';
export const CANCEL_LISTING_APPLICATION = 'CANCEL_LISTING_APPLICATION';
export const BUY_TOKENS_COMPLETE = 'BUY_TOKENS_COMPLETE';
export const UPDATE_TOKEN_INFORMATION = 'UPDATE_TOKEN_INFORMATION';
export const UPDATE_CANDIDATE_LISTINGS = 'UPDATE_CANDIDATE_LISTINGS';
export const APPROVE_REGISTRY_TOKENS = 'APPROVE_REGISTRY_TOKENS';
export const APPROVE_PLCR_TOKENS = 'APPROVE_PLCR_TOKENS';
export const APPROVE_PARAMETERIZER_TOKENS = 'APPROVE_PARAMETERIZER_TOKENS';
export const REQUEST_VOTING_RIGHTS = 'REQUEST_VOTING_RIGHTS';
export const WITHDRAW_VOTING_RIGHTS = 'WITHDRAW_VOTING_RIGHTS';

// token holder
export const CHALLENGE_START = 'CHALLENGE_START';
export const CHALLENGE_HIDE_TX_QUEUE = 'CHALLENGE_HIDE_TX_QUEUE';

export const SHOW_TX_QUEUE = 'SHOW_TX_QUEUE';
export const COMMIT_SHOW_TX_QUEUE = 'COMMIT_SHOW_TX_QUEUE';
export const COMMIT_HIDE_TX_QUEUE = 'COMMIT_HIDE_TX_QUEUE';
export const COMMIT_SEND = 'COMMIT_SEND';

export const REVEAL_SHOW_TX_QUEUE = 'REVEAL_SHOW_TX_QUEUE';
export const REVEAL_HIDE_TX_QUEUE = 'REVEAL_HIDE_TX_QUEUE';
export const REVEAL_SEND = 'REVEAL_SEND';

export const REFRESH_LISTING_STATUS = 'REFRESH_LISTING_STATUS';
export const REFRESH_LISTING_SEND = 'REFRESH_LISTING_SEND';

export const REQUEST_LISTINGS_TO_CLAIM_REWARD = 'REQUEST_LISTINGS_TO_CLAIM_REWARD';
export const UPDATE_LISTINGS_TO_CLAIM_REWARD = 'UPDATE_LISTINGS_TO_CLAIM_REWARD';

export const CLAIM_REWARD = 'CLAIM_REWARD';

export const REQUEST_CURRENT_LISTING = 'REQUEST_CURRENT_LISTING';
export const UPDATE_CURRENT_LISTING = 'UPDATE_CURRENT_LISTING';
export const CLEAR_CURRENT_LISTING = 'CLEAR_CURRENT_LISTING';
export const PROPOSE_NEW_PARAMETER_VALUE = 'PROPOSE_NEW_PARAMETER_VALUE';

