// app actions
export const APP_INIT = 'APP_INIT';
export const CHANGE_REGISTRY = 'CHANGE_REGISTRY';
export const CHANGE_BACKEND_USAGE = 'CHANGE_BACKEND_USAGE';

// advertiser
export const REQUEST_ADVERTISER_DOMAINS = 'REQUEST_ADVERTISER_DOMAINS';
export const GET_LISTING_DATA = 'GET_LISTING_DATA';
export const UPDATE_ADVERTISER_DOMAINS = 'UPDATE_ADVERTISER_DOMAINS';
export const UPDATE_LISTING_DATA = 'UPDATE_LISTING_DATA';

// publisher
export const BUY_TOKENS = 'BUY_TOKENS';
export const REQUEST_TOKEN_INFORMATION = 'REQUEST_TOKEN_INFORMATION';
export const SEND_TEST_TXS = 'SEND_TEST_TXS';
export const REQUEST_PUBLISHER_DOMAINS = 'REQUEST_PUBLISHER_DOMAINS';
export const APPLY_DOMAIN = 'APPLY_DOMAIN';
export const HIDE_TX_QUEUE = 'HIDE_TX_QUEUE';
export const CANCEL_DOMAIN_APPLICATION = 'CANCEL_DOMAIN_APPLICATION';

// token holder
export const CHALLENGE_START = 'CHALLENGE_START';
export const CHALLENGE_HIDE_TX_QUEUE = 'CHALLENGE_HIDE_TX_QUEUE';

export const COMMIT_SHOW_TX_QUEUE = 'COMMIT_SHOW_TX_QUEUE';
export const COMMIT_HIDE_TX_QUEUE = 'COMMIT_HIDE_TX_QUEUE';
export const COMMIT_SEND = 'COMMIT_SEND';

export const REVEAL_SHOW_TX_QUEUE = 'REVEAL_SHOW_TX_QUEUE';
export const REVEAL_HIDE_TX_QUEUE = 'REVEAL_HIDE_TX_QUEUE';
export const REVEAL_SEND = 'REVEAL_SEND';

export const REFRESH_LISTING_STATUS = 'REFRESH_LISTING_STATUS';
export const REFRESH_LISTING_SEND = 'REFRESH_LISTING_SEND';

